#!/bin/bash
sudo apt-get update
sudo apt-get install phpmyadmin php-mbstring php-gettext
sudo phpenmod mcrypt
sudo phpenmod mbstring
sudo systemctl restart apache2

##Edite o arquivo “/etc/apache2/apache2.conf”:

#echo Include /etc/phpmyadmin/apache.conf2 >> /etc/apache2/apache2.conf

#sudo systemctl restart apache2
